Merge barney and fbossctl build/package scripts (#886)

diff --git a/arista/fbossctl b/arista/fbossctl
--- a/arista/fbossctl
+++ b/arista/fbossctl
@@ -19,7 +19,7 @@ if [[ -z "${CENTOS_RELEASE}" ]]; then
    CENTOS_RELEASE="${DEFAULT_CENTOS_RELEASE}"
 fi
 
-FBOSS_IMG="docker.corp.arista.io/fboss-centos${CENTOS_RELEASE}:latest"
+FBOSS_IMG="barney-docker.infra.corp.arista.io/code.arista.io/os/fboss-centos--fboss-centos-image-el${CENTOS_RELEASE}"
 
 DEFAULT_DOCKER_NAME="FBOSS_CENTOS${CENTOS_RELEASE}-1-${USER}"
 if [[ -z "${DOCKER_NAME}" ]]; then
@@ -32,6 +32,10 @@ FBOSS_REPO_DIR="$(git rev-parse --show-toplevel)"
 FBOSS_BUILD_DIR="${FBOSS_REPO_DIR}/fboss-build"
 FBOSS_HOST_DIR="${FBOSS_BUILD_DIR}/FBOSS_DIR"
 FBOSS_RPM_DIR="${FBOSS_HOST_DIR}/rpmbuild/RPMS/"
+FBOSS_SCRATCH_DIR="$FBOSS_CONTAINER_BASE/tmp_build_dir"
+KERNEL_DIR_NAME="kernel-$FBOSS_LINUX_KERNEL"
+KERNEL_PATH="$FBOSS_CONTAINER_BASE/$KERNEL_DIR_NAME"
+SAI_SDK_DIR="$FBOSS_CONTAINER_BASE/built-sai-sdk"
 
 prog="$0"
 
@@ -79,96 +83,48 @@ maybe_pull_docker_image() {
    fi
 }
 
+declare -A kernel_map=( ["6.4"]="FBOSS_KERNEL_SRC_6.4.3-0_fbk747_rc2_1199_ga95cd85c72c4.tar.gz" )
+kernel_pull() {
+   kerneltar=${kernel_map["$1"]}
+   if [ -z "${kerneltar}" ]; then
+      echo "Unsupported kernel version: $1"; exit 1
+   fi
+   echo "Using Linux Kernel version $1 from $kerneltar"
+   # Download the specified kernel headers from dist and extract it
+   wget http://dist.sjc.aristanetworks.com/storage/fboss/fbossImageFiles/$kerneltar -O /tmp/kernel.tar
+   mkdir -p $2
+   tar xf /tmp/kernel.tar -C $2 --strip-components 1
+}
+
 maybe_setup_build_env() {
    # Setup the build environment by cloning SAI + SDK and creating the
    # local FBOSS directory.
 
-   # Select kernel.
-   if [[ "${FBOSS_LINUX_KERNEL}" == "5.12" ]]; then
-      KERNEL_TAR="FBOSS_KERNEL_SRC_5.12.0-0_fbk2_3390_g7ecb4ac46d7f.tar.gz"
-   elif [[ "${FBOSS_LINUX_KERNEL}" == "5.19" ]]; then
-      KERNEL_TAR="FBOSS_KERNEL_SRC_5.19.0.tar.gz"
-   elif [[ "${FBOSS_LINUX_KERNEL}" == "4.18" ]]; then
-      KERNEL_TAR="FBOSS_KERNEL_SRC_4.18.0-408.el8.x86_64.tar.gz"
-   elif [[ "${FBOSS_LINUX_KERNEL}" == "6.4" ]]; then
-      KERNEL_TAR="FBOSS_KERNEL_SRC_6.4.3-0_fbk747_rc2_1199_ga95cd85c72c4.tar.gz"
-   else
-      echo "Unsupported kernel version: ${FBOSS_LINUX_KERNEL}"
-      exit 1
+   kernel_host_path="$FBOSS_HOST_DIR/$KERNEL_DIR_NAME"
+   echo $kernel_host_path
+   if [ -z ${kernel_map["$FBOSS_LINUX_KERNEL"]} ]; then
+      echo "Unsupported kernel version: $FBOSS_LINUX_KERNEL"; exit 1
    fi
-   echo "Using Linux Kernel ${FBOSS_LINUX_KERNEL} from ${KERNEL_TAR}"
 
-   if [[ -d "${FBOSS_HOST_DIR}" ]] && [[ -f "${FBOSS_HOST_DIR}/${KERNEL_TAR}" ]]; then
+   if [[ -d "${FBOSS_HOST_DIR}" ]] && [[ -d "$kernel_host_path" ]]; then
       echo "Found build environment in ${FBOSS_HOST_DIR}, skipping setup"
       return
-   elif [[ -d "${FBOSS_HOST_DIR}" ]] && [[ ! -f "${FBOSS_HOST_DIR}/${KERNEL_TAR}" ]]; then
+   elif [[ -d "${FBOSS_HOST_DIR}" ]] && [[ ! -d "$kernel_host_path" ]]; then
       echo "Build environment found but has wrong linux kernel. Cleaning up and rebuilding."
       cleanup_build_env
    fi
 
    echo "Creating build environment in ${FBOSS_HOST_DIR}"
    set -ex
-   mkdir -p "${FBOSS_BUILD_DIR}"
-   mkdir "${FBOSS_HOST_DIR}"
+   mkdir -p "${FBOSS_HOST_DIR}"
    cd "${FBOSS_HOST_DIR}"
 
-   # Clone the SAI + SDK and download patches.
-   git clone git@github.com:aristanetworks/Aqua_SAI.git
-   cd "${FBOSS_HOST_DIR}/Aqua_SAI"
-   git pull
-   git checkout eos-trunk
-   # Use patch0-Jupiter-SAI-Makefile.patch w/SAI < 10.0.0
-   wget http://dist/storage/fboss/FBOSS-SAI/patch4-Jupiter-SAI-Makefile.patch
-   git apply patch4-Jupiter-SAI-Makefile.patch
-   cd "${FBOSS_HOST_DIR}/Aqua_SAI/sdk-src/hsdk_6.5.30_SAI_11.7.0_GA"
-   sdk_file="sai-sdk-all-6.5.30-fdc8836cc1.tar.xz"
-   wget http://dist/storage/fboss/FBOSS-SAI/$sdk_file
-   tar -xf "$sdk_file"
-   # Patch Broadcom DNX kernel module make file fixes for SDK 6.5.29
-   wget http://dist/storage/fboss/FBOSS-SAI/patch3-SDK-6_5_30_DNX_Kernel_Module_fixes-EDK.patch
-   patch "dnx-sdk-6.5.30-gpl-modules/make/Make.config" < patch3-SDK-6_5_30_DNX_Kernel_Module_fixes-EDK.patch
-   # Patch to skip check for proto R3 ASICs.
-   wget http://dist/storage/fboss/FBOSS-SAI/patch11-SDK-6_5_29-Ramon3-proto-fix.patch
-   patch "hsdk-all-6.5.30/src/soc/dnxc/drv.c" -p1 < patch11-SDK-6_5_29-Ramon3-proto-fix.patch
-   # Patch to rename get_time for centos9 build (collides with the same symbol in
-   # iproute2)
-   wget http://dist/storage/fboss/FBOSS-SAI/patch12-SDK-6_5_29-get_time-symbol-fix.patch
-   patch "hsdk-all-6.5.30/src/appl/diag/gdpll.c" -p1 < patch12-SDK-6_5_29-get_time-symbol-fix.patch
-
-   # Patch bcm-knet.c kernel module to workaround some missing netdev_* API calls in
-   # the kernel we are building. Should be available in the 6.x kernels.
-   wget http://dist/storage/fboss/FBOSS-SAI/patch15-SDK-6_5_30_SP1_bcm-knet-build-fixes.patch
-   patch "dnx-sdk-6.5.30-gpl-modules/systems/linux/kernel/modules/bcm-knet/bcm-knet.c" < patch15-SDK-6_5_30_SP1_bcm-knet-build-fixes.patch
-
-   # Kernel 5.19 patches.
-   if [[ "${FBOSS_LINUX_KERNEL}" == "5.19" ]] || [[ "${FBOSS_LINUX_KERNEL}" == "6.4" ]]; then
-      # We need to fix some conflicting build options and fix the linux-user-bde Makefile
-      # to support NO_PRECOMPILED_MODULE=1.
-      wget http://dist/storage/fboss/FBOSS-SAI/patch9-SDK-5.19-post-SDK-6_5_30.patch
-      patch -p1 < patch9-SDK-5.19-post-SDK-6_5_30.patch
-   fi
-
-   # Kernel 6.4 patches.
-   if [[ "${FBOSS_LINUX_KERNEL}" == "6.4" ]]; then
-      # Need to adjust for breaking change in netif_napi_add parameters.
-      wget http://dist/storage/fboss/FBOSS-SAI/patch16-SDK-6.4-post-SDK-6_5_30-bcm-knet-netif.patch
-      patch "dnx-sdk-6.5.30-gpl-modules/systems/linux/kernel/modules/bcm-knet/bcm-knet.c" < patch16-SDK-6.4-post-SDK-6_5_30-bcm-knet-netif.patch
-   fi
-
-   # Centos 9 build related deps
-   if [[ "${CENTOS_RELEASE}" == "9" ]];
-   then
-      # Copy deps required for centos 9 build.
-      # libnsl.a needs to be copied over to /usr/lib64 in the container.
-      cd "${FBOSS_HOST_DIR}"
-      wget http://dist/storage/fboss/FBOSS-SAI/el9/libnsl.a
-   fi
+   # Clone SAI and SDK repositories
+   git clone "ssh://$USER@gerrit.corp.arista.io:29418/fboss-bcm-sai"
+   git clone "ssh://$USER@gerrit.corp.arista.io:29418/fboss-bcm-sdk"
 
    # Download FBOSS linux header files.
-   cd "${FBOSS_HOST_DIR}"
-   wget http://dist/storage/fboss/fbossImageFiles/"${KERNEL_TAR}"
-   tar -xf "${KERNEL_TAR}"
-   set +ex
+   kernel_pull "$FBOSS_LINUX_KERNEL" "$kernel_host_path"
 }
 
 cleanup_build_env() {
@@ -183,8 +139,6 @@ setup() {
    maybe_setup_build_env
    # Docker run's volume mount can't handle symlinks, so copy the latest versions
    # of the build scripts every time.
-   cp -f "${FBOSS_REPO_DIR}"/arista/build-utils/build.sh "${FBOSS_HOST_DIR}"
-   cp -f "${FBOSS_REPO_DIR}"/arista/build-utils/package.sh "${FBOSS_HOST_DIR}"
    cp -f "${FBOSS_REPO_DIR}"/arista/core/scripts/run_sw_tests.sh "${FBOSS_HOST_DIR}"
    cp -f "${FBOSS_REPO_DIR}"/arista/util/bsp-mapping-gen/bspMappingGen.sh "${FBOSS_HOST_DIR}"
    cp -f "${FBOSS_REPO_DIR}"/arista/util/platform-mapping-gen/platformMappginGen.sh "${FBOSS_HOST_DIR}"
@@ -223,14 +177,61 @@ enter_container_shell() {
 
 do_build() {
    setup
-   run_cmd_container bash build.sh $@ --kernel "${FBOSS_LINUX_KERNEL}"
+   fboss_args=()
+   while [[ $# -gt 0 ]]; do
+      case $1 in
+         --rebuild-all)
+            rebuild_all=1
+            shift
+            ;;
+         --arch)
+            if [[ "$2" == "dnx" ]]; then
+               arch="$2"
+               sdkVersion=6.5.30
+               saiVersion=11.7.0
+            elif [[ "$2" == "xgs" ]]; then
+               arch="$2"
+               sdkVersion=6.5.29
+               saiVersion=10.2.0
+            else
+               echo "Invalid architecture. Choose between: xgs dnx"; exit 1
+            fi
+            shift; shift
+            ;;
+         --* | --*)
+            fboss_args+=$1
+            shift
+            ;;
+      esac
+   done
+   set -ex
+   if ! [[ -z $rebuild_all ]]; then
+      # Clean build and export SDK
+      run_cmd_container ./fboss-bcm-sdk/build.py clean -a $arch -v $sdkVersion
+      run_cmd_container ./fboss-bcm-sdk/build.py build -a $arch -v $sdkVersion \
+                        -k "$FBOSS_LINUX_KERNEL"
+      run_cmd_container ./fboss-bcm-sdk/build.py export -a $arch -v $sdkVersion \
+                        -e $FBOSS_CONTAINER_BASE/built-sai-sdk
+
+      # Clean build and export SAI
+      run_cmd_container ./fboss-bcm-sai/build.py clean -a $arch -v $saiVersion 
+      run_cmd_container ./fboss-bcm-sai/build.py build -a $arch -v $saiVersion \
+                        -s $FBOSS_CONTAINER_BASE/fboss-bcm-sdk/sdk-$sdkVersion
+      run_cmd_container ./fboss-bcm-sai/build.py export -a $arch -v $saiVersion \
+                        -e $FBOSS_CONTAINER_BASE/built-sai-sdk
+   fi
+   run_cmd_container bash ./fboss.git/build.sh ${fboss_args[@]} --arch $arch \
+                     --kernel-dir "$KERNEL_PATH" --scratch-dir "$FBOSS_SCRATCH_DIR" \
+                     --sai-sdk-dir "$SAI_SDK_DIR" ${rebuild_all+--rebuild-fboss}
    # Restore files that have potentially been clobbered by the FBOSS build process.
    sudo git -C "$FBOSS_REPO_DIR" restore "build/*"
 }
 
 do_package() {
    setup
-   run_cmd_container bash package.sh $@
+   set -ex
+   run_cmd_container bash fboss.git/package.sh --scratch-dir "$FBOSS_SCRATCH_DIR" \
+                     --sai-sdk-dir "$SAI_SDK_DIR" --export-dir "$FBOSS_CONTAINER_BASE/rpmbuild" $@
 }
 
 do_update_dut() {
@@ -315,6 +316,9 @@ case "${command}" in
       ;;
    bsp_mapping_gen)
       do_bsp_mapping_gen
+      ;;
+   kernel_pull)
+      kernel_pull $@
       ;;
    platform_mapping_gen)
       do_platform_mapping_gen $1
