FBOSS SWI improvements
This PR introduces the following improvements to the FBOSS SWI:

1\. Use the SWI path found in boot-config rather than assuming it is
named FBOSS.swi.

2\. Start services automatically.

3\. Allow console speeds rather than the default. Whatever is used
in Aboot will be used when booting FBOSS. This allows FBOSS console
to be visible if the CONSOLESPEED aconfctl parameter is set.

Test Plan

Built SWI as follows:
```
./build_swi.sh dnx 6.4 /tmp/FbossSWI
swi sign --dev-ca --force-sign /tmp/FbossSWI/FBOSS.swi
```

1\. Verified that if the SWI is named Fboss-XXX.swi rather than the default
FBOSS.swi, FBOSS was still bootable

Verified that fboss services were started.

2\. Verified that using a non-default console speed of 57600, FBOSS booted
and console was visible.

3\. Ran the FbossTest/FbossOssSanitizeSwiTest

diff --git a/swi-modules/initializeFboss b/swi-modules/initializeFboss
--- a/swi-modules/initializeFboss
+++ b/swi-modules/initializeFboss
@@ -3,7 +3,16 @@
 echo "INITIALIZING FBOSS"
 
 mkdir -p "/tmp/SWI"
-unzip -oq "/run/initramfs/overlayfs/FBOSS.swi" -d /tmp/SWI
+swiDir="/run/initramfs/overlayfs"
+swiUrl=$( grep -v '^#' $swiDir/boot-config | grep 'SWI=' | awk -F '=' '{print $2}' )
+swiRelPath=$(echo $swiUrl | sed -E "s,^(.*):/+([^/]*)+,\2,")
+if [ -z "$swiRelPath" ]; then
+   echo "Failed to parse SWI path from boot-config. Assuming FBOSS.swi"
+   swiRelPath="FBOSS.swi"
+fi
+swiPath="$swiDir/$swiRelPath"
+
+unzip -oq "$swiPath" -d /tmp/SWI
 
 swi_dir="/tmp/SWI"
 
@@ -33,9 +42,18 @@ for keyword in $core_rpm_keywords; do
     install_rpm_by_keyword "$keyword"
 done
 
+services="platform_manager \
+   sensor_service \
+   fan_service \
+   data_corral_service \
+   qsfp_service \
+   fboss_sw_agent \
+   fboss_hw_agent@0"
+
 case "$system_product" in
     "MERU800BFA")
         install_rpm_by_keyword "meru800bfa-"
+        services="$services fboss_hw_agent@1"
         ;;
     "MERU800BIA")
         install_rpm_by_keyword "meru800bia-"
@@ -48,6 +66,7 @@ case "$system_product" in
         ;;
     *)
         echo "Unknown product: $system_product. No additional RPMs installed."
+        exit 1
         ;;
 esac
 
@@ -56,5 +75,12 @@ if [ $? -ne 0 ]; then
     echo "Failed to run fboss_init.sh"
     exit 1
 fi
+
+echo -n "Starting FBOSS services..."
+for service in $services; do
+   systemctl enable $service
+   systemctl start $service
+done
+echo "Done"
 
 exit 0
