check generate config diff only in workflow, run on pr

diff --git a/.github/workflows/check-current-configs.yaml b/.github/workflows/check-current-configs.yaml
--- a/.github/workflows/check-current-configs.yaml
+++ b/.github/workflows/check-current-configs.yaml
@@ -1,7 +1,11 @@
-name: Automatically Update Platform Configs on Change
+name: Check For Missing Platform Configs Changes
 
 on:
   push:
+    paths:
+      - 'arista/util/configs-and-diagrams/GenerateConfigsAndDiagrams/BaseConfigs.py'
+      - 'arista/util/configs-and-diagrams/GenerateConfigsAndDiagrams/Platforms/**'
+  pull_request:
     paths:
       - 'arista/util/configs-and-diagrams/GenerateConfigsAndDiagrams/BaseConfigs.py'
       - 'arista/util/configs-and-diagrams/GenerateConfigsAndDiagrams/Platforms/**'
@@ -24,20 +28,20 @@ jobs:
         python -m pip install --upgrade pip
         pip install diagrams
 
-    - name: Update JSON configs for all platforms
+    - name: Check JSON configs for all platforms
       run: |
         cd arista/util/configs-and-diagrams
         python generate.py --update_all_configs
 
-        git config --global user.name "GitHub Actions"
-        git config --global user.email "actions@github.com"
-
         git add ../../../fboss/platform/configs/*
 
-        if git diff --cached --quiet; then
-          echo "No changes to commit. Exiting..."
+        if ! git diff --cached --quiet; then
+          echo "Changes to JSON configs are required."
+          echo "Please run the config generation tool locally and commit the changes."
+          echo "  cd arista/util/configs-and-diagrams"
+          echo "  python generate.py --update_all_configs"
+          exit 1
+        else
+          echo "No changes to JSON configs needed."
           exit 0
         fi
-
-        git commit -m "Automatically update all JSON configs"
-        git push
